services:
  - type: web
    name: devlokwebsite
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn devlokwebsite.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2